Vagrant.configure("2") do |config|
  
    config.vm.define "FlareVM" do |flare|
      flare.vm.box = "stretfordStart/FlareVM"
      flare.vm.guest = :windows
      flare.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.cpus = 2
      end
    end
  
    config.vm.define "REMnux" do |remnux|
      remnux.vm.box = "stretfordStart/REMnux"
      remnux.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.cpus = 2
      end
    end
  
  end
  
