Vagrant.configure("2") do |config|
  # Use a generic Ubuntu 20.04 image
  config.vm.box = "generic/ubuntu2004"

  # Run updates
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
  SHELL

  # Install gnome desktop environment
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y gnome-core
  SHELL

  # Install VSCode
  config.vm.provision "shell", inline: <<-SHELL
    sudo snap install --classic code
  SHELL

  # Adjusted REMnux installation
  config.vm.provision "shell", inline: <<-SHELL
    wget https://REMnux.org/remnux-cli
    if [ $(sha256sum remnux-cli | awk '{print $1}') = "88cd35b7807fc66ee8b51ee08d0d2518b2329c471b034ee3201e004c655be8d6" ]; then
      mv remnux-cli remnux
      chmod +x remnux
      sudo mv remnux /usr/local/bin
      sudo apt-get install -y gnupg
      sudo remnux install
    else
      echo "Hashes do not match. Exiting."
    fi
  SHELL

  # Install and enable qemu-guest-agent
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y qemu-guest-agent
    sudo systemctl enable qemu-guest-agent
    sudo systemctl start qemu-guest-agent
  SHELL

  # Add user remnux with password malware
  config.vm.provision "shell", inline: <<-SHELL
    sudo useradd -m -p $(openssl passwd -1 malware) remnux
  SHELL

  # Set locales
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y language-pack-en
    sudo locale-gen en_US.UTF-8
    sudo update-locale LANG=en_US.UTF-8
    sudo dpkg-reconfigure --frontend noninteractive locales
    sudo timedatectl set-timezone Europe/Zurich
    sudo localectl set-x11-keymap ch
  SHELL
end
