Vagrant.configure("2") do |config|
  
    config.vm.define "FlareVM" do |flare|
      flare.vm.box = "stretfordStart/FlareVM"
      flare.vm.guest = :windows
      flare.vm.provider "libvirt" do |lv|
        lv.driver = "kvm"
        lv.memory = 8192
        lv.cpus = 2
      end
    end
  
    config.vm.define "REMnux" do |remnux|
      remnux.vm.box = "stretfordStart/REMnux"
      remnux.vm.provider "libvirt" do |lv|
        lv.driver = "kvm"
        lv.memory = 8192
        lv.cpus = 2
      end
      remnux.vm.communicator = "ssh"
      remnux.ssh.insert_key = false
    end
  
  end
  
