Vagrant.configure("2") do |config|
  
    config.vm.define "FlareVM" do |flare|
      flare.vm.box = "jborean93/WindowsServer2019"
      flare.vm.guest = :windows
      flare.vm.provider "libvirt" do |lv|
        lv.driver = "kvm"
        lv.memory = 8192
        lv.cpus = 2
      end
      flare.vm.provision "shell", path: "flare_provision.ps1"
    end
  
    config.vm.define "REMnux" do |remnux|
      remnux.vm.box = "generic/ubuntu2004"
      remnux.vm.provider "libvirt" do |lv|
        lv.driver = "kvm"
        lv.memory = 8192
        lv.cpus = 2
      end
      remnux.vm.communicator = "ssh"
      remnux.ssh.insert_key = false
      remnux.vm.provision "shell", path: "remnux_provision.sh"
    end
  
  end
  
