Vagrant.configure("2") do |config|
  
    config.vm.define "Flare" do |flare|
      flare.vm.box = "peru/windows-10-enterprise-x64-eval"
      flare.vm.box_version = "20231001.01"
      flare.vm.guest = :windows
      flare.disksize-size = '80GB'

      flare.vm.provider "libvirt" do |lv|
        lv.driver = "kvm"
        lv.memory = 8192
        lv.cpus = 2
      end
    end
  
    config.vm.define "REMnux" do |remnux|
      remnux.vm.box = "generic/Ubuntu"
      remnux.disksize-size = '50GB'
      remnux.vm.provider "libvirt" do |lv|
        lv.driver = "kvm"
        lv.memory = 8192
        lv.cpus = 2
      end

      remnux_config.vm.provision "shell", path: "remnux_provision.sh"
    end
  
  end
  